//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer.DataBaseFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DealerDBEntities : DbContext
    {
        private static DealerDBEntities _context;

        public DealerDBEntities()
            : base("name=DealerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static DealerDBEntities GetContext()
        {
            if (_context == null)
                _context = new DealerDBEntities();
            return _context;
        }

        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Order_ACTM> Order_ACTM { get; set; }
        public virtual DbSet<PickUpPoint> PickUpPoints { get; set; }
        public virtual DbSet<Production_ACTM> Production_ACTM { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
