//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer.DataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_ACTM
    {
        public int Id { get; set; }
        public Nullable<int> ACTM_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> PickUpPoint_Id { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int Quantity { get; set; }
        public int Order_Price { get; set; }
        public Nullable<int> Delivery_Price { get; set; }
        public Nullable<int> Order_sum { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Production_ACTM Production_ACTM { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
    }
}
